name: Test PR
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          cache-dependency-path: |
            application/*.gradle*
            application/**/gradle-wrapper.properties

      - name: Bind Variable
        uses: microsoft/variable-substitution@v1
        with:
          files: '**/application*.yml'
        env:
          test: 'true'

      - name: Run Tests
        run: ./gradlew application:check

      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: 'application/build/test-results/test/**/*.xml'
          token: ${{ secrets.GITHUB_TOKEN }}